// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB87xUUWwEHTqiZWYero94zt4gNJi0lQzo',
    appId: '1:758055765478:web:ec8252cb0dad43fd0c0227',
    messagingSenderId: '758055765478',
    projectId: 'dereje-hailemariam',
    authDomain: 'dereje-hailemariam.firebaseapp.com',
    storageBucket: 'dereje-hailemariam.firebasestorage.app',
    measurementId: 'G-VQM6YY0BC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXPQb0_OLfDvCpVCF7sITnnVchmKrhptg',
    appId: '1:758055765478:android:d524a008aee408560c0227',
    messagingSenderId: '758055765478',
    projectId: 'dereje-hailemariam',
    storageBucket: 'dereje-hailemariam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_4BIGjvfTPfwhik1LxPeJ3oqCveGYE0o',
    appId: '1:758055765478:ios:d1b0c0573a6456ee0c0227',
    messagingSenderId: '758055765478',
    projectId: 'dereje-hailemariam',
    storageBucket: 'dereje-hailemariam.firebasestorage.app',
    iosBundleId: 'hailemariam013.com.portfolio',
  );
}
